steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['ls','app', 'deploy', '/workspace/.../target/self-information-0.0.1-SNAPSHOT/WEB-INF/appengine-web.xml']