runtime: java8
manual_scaling:
  instances: 1
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: /.*
  script: unused
  login: optional
  secure: optional
